[package]
name = "variables"
version = "3.1.2"
authors = ["Almir Neto <almir@dienekes.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
